import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/styles/globals.css";
import Sidenav from "@/app/ui/components/Sidenav";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans font-medium antialiased bg-surface`}>
        <div className="flex min-h-screen">
          <Sidenav />
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
